spring:
  application:
    name: zuul-gateway-service
server:
  port: 8762
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

zuul:
    routes:
        sweetitem-service:
            path: /sweetitem-service/**
            service-id: sweetitem-service
        cart-service:
            path: /cart-service/**
            service-id: cart-service
        authentication-service:
            path: /auth/**
            sensitive-headers: 'Cookie,Set-Cookie  '
            service-id: authentication-service
            strip-prefix: false
logging:
    level:
        com:
            cognizant:
                zuulgatewayservice: DEBUG
            